services:
  leetngreet-app:
    container_name: leetngreet-app
    build:
      context: ./leetngreet
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    develop:
      watch:
        - action: sync
          path: ./app
          target: /src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./leetngreet/src:/app/src
      - ./leetngreet/public:/app/public
      - /app/node_modules
    depends_on:
      - leetngreet-database
    restart: always
    ports:
      - 3000:3000
    command: npm run dev
    networks:
      - leetngreet_network

  # Add more containers below (nginx, postgres, etc.)
  leetngreet-database:
    container_name: leetngreet-db
    image: mongo:6
    #volumes: 
    #  - database:/data/db
    ports:
      - 27017:27017

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  leetngreet_network:
    external: true